import numpy as np
import os

print("--- Generating C++ Table Directly from NPY ---")

# 1. Load the true .npy file (ensure this is the right folder!)
npy_path = r'C:\Users\tdhus\Desktop\SEP + SEDDP\2026 - Earth Horizon Sensor for Delfi-Twin\data_package\Horizon_detection_C++\conversion_table.npy'
output_cpp_path = r'C:\Users\tdhus\Desktop\SEP + SEDDP\2026 - Earth Horizon Sensor for Delfi-Twin\data_package\Horizon_detection_C++\ConversionTable.cpp'

if not os.path.exists(npy_path):
    raise FileNotFoundError(f"Could not find {npy_path} in the current directory!")

table = np.load(npy_path)
num_rows = table.shape[0]
SCALER = 4096

print(f"Loaded {num_rows} rows.")

# 2. Open the C++ file for writing
output_dir = os.path.dirname(output_cpp_path)
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

with open(output_cpp_path, "w") as f:
    f.write('#include "HorizonTypes.hpp"\n\n')
    f.write("// AUTOGENERATED FILE - DO NOT EDIT\n")
    f.write(f"const int TABLE_SIZE = {num_rows};\n\n")
    f.write("const LookupEntry CONVERSION_TABLE[] = {\n")
    
    # 3. Scale and write directly to text
    for row in table:
        # row mapping: [Pitch(0), Roll(1), vx(2), vy(3), area(4), atan2(5)]
        pitch_val = int(row[0] * SCALER)
        roll_val  = int(row[1] * SCALER)
        vx_val    = int(row[2] * SCALER)
        vy_val    = int(row[3] * SCALER)
        area_val  = int(row[4] * SCALER)
        atan2_val = int(row[5] * SCALER)
        
        f.write(f"    {{{roll_val}, {pitch_val}, {vx_val}, {vy_val}, {area_val}, {atan2_val}}},\n")
        
    f.write("};\n")

print(f"Success! {output_cpp_path} created.")

# 4. Immediate Verification 
print("\n--- Verification ---")
print("Expected First Row in C++:")
print(f"{{{int(table[0, 1] * SCALER)}, {int(table[0, 0] * SCALER)}, "
      f"{int(table[0, 2] * SCALER)}, {int(table[0, 3] * SCALER)}, "
      f"{int(table[0, 4] * SCALER)}, {int(table[0, 5] * SCALER)}}}")
