#include "earth_sensor.hpp"
#include <cmath>
#include <float.h>

/* These are defined in the files generated by your Python script */
extern const FixedEntry conversion_table_pow2[];
extern const uint32_t TABLE_SIZE;

/* You should also convert your X/Y angle text files to static arrays like these */
extern const float X_angles_rad[768];
extern const float Y_angles_rad[768];

const float SCALER = 4096.0f; // 2^12

AttitudeResult calculate_attitude(const float* mlx_data) {
    float sum_x = 0.0f, sum_y = 0.0f, area = 0.0f;
    int count = 0;
    AttitudeResult result = {0.0f, 0.0f, false};

    // 1. Vector and Area Integration
    for (int i = 0; i < 768; i++) {
        if (mlx_data[i] > 35.0f) { // Threshold for Earth detection
            count++;
            sum_x += (X_angles_rad[i]);
            sum_y += (Y_angles_rad[i]);
            area += 1.0f; 
        }
    }

    // Quality check: avoid calculation if Earth is not in view or sensor is saturated
    if (count < 20 || count > 740) return result;

    float mag = sqrtf(sum_x * sum_x + sum_y * sum_y);
    float vx = sum_x / mag;
    float vy = sum_y / mag;
    float normalized_area = area / 768.0f; 

    // 2. Nearest Neighbor Search in Flash Memory
    float min_dist = FLT_MAX;
    for (uint32_t i = 0; i < TABLE_SIZE; i++) {
        float tvx = (float)conversion_table_pow2[i].vx / SCALER;
        float tvy = (float)conversion_table_pow2[i].vy / SCALER;
        float tarea = (float)conversion_table_pow2[i].area / SCALER;

        // Euclidean distance for matching
        float dist = powf(vx - tvx, 2) + powf(vy - tvy, 2) + powf(normalized_area - tarea, 2);

        if (dist < min_dist) {
            min_dist = dist;
            result.pitch = (float)conversion_table_pow2[i].pitch / SCALER;
            result.roll = (float)conversion_table_pow2[i].roll / SCALER;
            result.valid = true;
        }
    }

    return result;
}