
#include "HorizonDetector.hpp"
#include <math.h>

// These link to your autogenerated SensorGeometry.cpp and your flashed binary table
extern const int32_t X_ANGLES_FIXED[768];
extern const int32_t Y_ANGLES_FIXED[768];
extern const int32_t PIXEL_AREA_FIXED[768];
extern const LookupEntry CONVERSION_TABLE[];
extern const int TABLE_SIZE;

bool HorizonDetector::process_frame(const float* frame_data, float& local_pitch, float& local_roll) {
    int32_t sum_x_fixed = 0, sum_y_fixed = 0, total_area_fixed = 0;
    int valid_pixels = 0;

    // Single pass accumulation 
    for (int i = 0; i < PIXELS_PER_SENSOR; i++) {
        if (frame_data[i] > THRESHOLD_TEMP) {
            sum_x_fixed += X_ANGLES_FIXED[i];
            sum_y_fixed += Y_ANGLES_FIXED[i];
            total_area_fixed += PIXEL_AREA_FIXED[i];
            valid_pixels++;
        }
    }

    if (valid_pixels < 20 || valid_pixels > 748) return false;

    // Normalize magnitude
    float sum_x_f = (float)sum_x_fixed / SCALER;
    float sum_y_f = (float)sum_y_fixed / SCALER;
    float mag = sqrtf(sum_x_f * sum_x_f + sum_y_f * sum_y_f);
    if (mag == 0.0f) return false;

    int32_t v_x_fixed = (int32_t)((sum_x_f / mag) * SCALER);
    int32_t v_y_fixed = (int32_t)((sum_y_f / mag) * SCALER);

    int32_t pitch_fixed, roll_fixed;
    if (perform_banded_search(v_x_fixed, v_y_fixed, total_area_fixed, pitch_fixed, roll_fixed)) {
        local_pitch = (float)pitch_fixed / SCALER;
        local_roll = (float)roll_fixed / SCALER;
        return true;
    }
    return false;
}

bool HorizonDetector::perform_banded_search(int32_t v_x_fixed, int32_t v_y_fixed, int32_t area_fixed, 
                                            int32_t& out_pitch_fixed, int32_t& out_roll_fixed) {
    float approx_roll = atan2f((float)v_y_fixed, (float)v_x_fixed);
    int32_t approx_roll_fixed = (int32_t)(approx_roll * SCALER);
    
    int32_t tolerance = (int32_t)(0.15f * SCALER);
    int32_t pi_fixed = (int32_t)(M_PI * SCALER);
    
    int32_t lower_bound = approx_roll_fixed - tolerance;
    int32_t upper_bound = approx_roll_fixed + tolerance;
    int32_t lower_wrap = 999999, upper_wrap = -999999;

    if (upper_bound > pi_fixed) {
        lower_wrap = -pi_fixed;
        upper_wrap = upper_bound - 2 * pi_fixed;
    } else if (lower_bound < -pi_fixed) {
        lower_wrap = lower_bound + 2 * pi_fixed;
        upper_wrap = pi_fixed;
    }

    int64_t min_dist_sq = -1;
    int best_idx = -1;

    for (int i = 0; i < TABLE_SIZE; i++) {
        int32_t t_roll = CONVERSION_TABLE[i].atan2_val;
        if ((t_roll >= lower_bound && t_roll <= upper_bound) || 
            (t_roll >= lower_wrap && t_roll <= upper_wrap)) {
            
            int64_t dx = (int64_t)CONVERSION_TABLE[i].v_x - v_x_fixed;
            int64_t dy = (int64_t)CONVERSION_TABLE[i].v_y - v_y_fixed;
            int64_t da = (int64_t)CONVERSION_TABLE[i].area - area_fixed;
            int64_t dist_sq = (dx*dx) + (dy*dy) + (da*da);
            
            if (min_dist_sq == -1 || dist_sq < min_dist_sq) {
                min_dist_sq = dist_sq;
                best_idx = i;
            }
        }
    }

    // Reject poor matches and Pinhole Phantoms (Pitch > 90 deg)
    if (best_idx == -1 || min_dist_sq > 167772160LL) return false;
    if (CONVERSION_TABLE[best_idx].table_pitch > 368640) return false; // 90 * 4096

    out_roll_fixed = CONVERSION_TABLE[best_idx].table_roll;
    out_pitch_fixed = CONVERSION_TABLE[best_idx].table_pitch;
    return true;
}