
import numpy as np

# Choose a specific test file generated by your previous script
test_file = 'data/p25.0_r27.0.npy' 
data = np.load(test_file)

# Ensure it is float64 (double in C++)
data = data.astype(np.float64)

# Save as a raw binary file
data.tofile('test_frame.bin')
print("Successfully created test_frame.bin")
